pipeline {
    environment {
        registry = "https://docker.mjamsek.com"
        registryCredential = "mjamsek-hub"
        dockerImageTag = "docker.mjamsek.com/lozigorbox"
        dockerImage = ""
        version = ""
        taskerKey = "lozigorbox-tasker-key"
    }

    agent any

    tools {
        maven "maven3.6"
        nodejs "node11.6"
        jdk "jdk8"
    }

    stages {
        stage("Cloning git") {
            steps {
                git branch: "master",
                        credentialsId: "github-token",
                        url: "https://github.com/Jamsek-m/lozigor-box.git"
            }
        }
        stage("Set environment variables") {
            steps {
                script {
                    version = readFile('VERSION').trim()
                }
            }
        }
        stage("Preparing client") {
            steps {
                sh "npm install --prefix ./client"
            }
        }
        stage("Packaging application") {
            steps {
                sh "mvn clean package"
            }
        }
        stage("Building docker image") {
            steps {
                script {
                    dockerImage = docker.build dockerImageTag
                }
            }
        }
        stage("Publishing docker image") {
            steps {
                script {
                    docker.withRegistry(registry, registryCredential) {
                        dockerImage.push("$version")
                        dockerImage.push("latest")
                    }
                }
            }
        }
        stage("Removing generated docker images") {
            steps {
                sh "docker rmi $dockerImageTag:$version"
                sh "docker rmi $dockerImageTag:latest"
            }
        }
        stage("Deploying application") {
            steps {
                httpRequest consoleLogResponseBody: true, customHeaders: [[maskValue: true, name: 'X-Tasker-Key', value: taskerKey], [maskValue: false, name: 'X-Tasker-Name', value: 'lozigorbox']], httpMode: 'POST', requestBody: '{"actionName":"DockerPlugin.recreate","parameters":{"containerName":"lozigorbox","configDockerAPI":"DOCKER_API_0"}}', responseHandle: 'NONE', url: 'https://tasker.mjamsek.com/v1/actions/execute', validResponseCodes: '200'
                def response = httpRequest url: "http://tasker.mjamsek.com/v1/actions/execute", validResponseCodes: '200'
                if (response.status != 200) {
                    error("Healthcheck failed!")
                }
            }
        }
    }
}